version: 2
jobs:
  develop:
    docker:
      - image: circleci/python:3-node
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: yarn
          command: yarn
      - run:
          name: build
          command: yarn build
      - run:
          name: Install Aws
          command: pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync ~/build/public s3://dev-morcmtb-trails --delete
      # - run:
      #     name: CloudFront
      #     command: aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID_DEV --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - develop:
          filters:
            branches:
              only: develop
